name: Code Review with OpenAI

on:
  push:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch the last 2 commits to compare

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: |
        dotnet restore
        dotnet build

    - name: Get the diff of the latest commit
      id: diff
      run: |
        # Get the diff between the latest commit and the previous one
        git diff HEAD^ HEAD > commit_diff.txt
        echo "Commit diff saved to commit_diff.txt"

    - name: Use the diff in the next step
      run: |
        # Example: Print the diff to the console
        cat commit_diff.txt
        
    - name: Publish the API
      run: dotnet publish -c Release -o ./publish

    - name: Run the API
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
      run: |
        cd ./publish
        dotnet CodeReviewAssistant.dll &  # Run the API in the background
        sleep 5  # Wait for the API to start (adjust the sleep duration as needed)

    - name: Send the diff to the API
      run: |
        # Install jq (if not already installed)
        sudo apt-get install -y jq
    
        # Read and escape the diff content using jq
        DIFF_CONTENT=$(jq -sR . commit_diff.txt)
        
        # Send the diff to the API endpoint and save the response
        curl -X POST http://localhost:5000/api/Review/code \
          -H "Content-Type: application/json" \
          -d "{\"code\": $DIFF_CONTENT}" \
          -o response.txt
        
        # Print the API response to the console
        echo "API Response:"
        cat response.txt
