name: Code Review with OpenAI

on:
  push:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: |
        dotnet restore
        dotnet build

    - name: Get the diff of the PR
      id: diff
      run: |
        PR_DIFF=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3.diff" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files)
        
        # Extract the diffs from the response
        echo "PR Diff: $PR_DIFF"
        
        # Save the diff in a file to use in the next step
        echo "$PR_DIFF" > pr_diff.txt
