name: Code Review with OpenAI

on:
  push:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: |
        dotnet restore
        dotnet build

    - name: Get the diff of the PR
      id: diff
      run: |
        # Fetch the pull request diff using the GitHub API
        PR_DIFF=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3.diff" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
        
        # Check if the API request was successful
        if [ -z "$PR_DIFF" ]; then
          echo "Error: Failed to fetch PR diff"
          exit 1
        fi
        
        # Save the diff to a file
        echo "$PR_DIFF" > pr_diff.txt
        echo "PR diff saved to pr_diff.txt"

    - name: Use the diff in the next step
      run: |
        # Example: Print the diff to the console
        cat pr_diff.txt
